version: '3.8'

services:
  db:
    image: postgres:16
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: odoo:18.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: odoo_nginx_proxy
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_webroot:/var/www/certbot:ro
      - certbot_certs:/etc/letsencrypt:ro
    env_file:
      - .env
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: odoo_certbot_renewer
    volumes:
      - certbot_webroot:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    entrypoint:
      - sh
      - -c
      - |
        trap exit TERM;
        while :; do
          certbot renew;
          sleep 12h & wait $$!;
        done;
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_web_data:
  certbot_webroot:
  certbot_certs:
