version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: radiksen-odoo:18.0
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      # Use the environment variable for the password
      - PASSWORD=${ODOO_DB_PASSWORD}
    restart: always

  db:
    image: postgres:16
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      # Use the environment variable for the password
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: odoo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the main Nginx configuration file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Volume for Certbot's ACME challenge files
      - certbot-web:/var/www/certbot
      # Volume for Let's Encrypt certificates
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    container_name: odoo_certbot
    volumes:
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    # This entrypoint command runs a loop to renew certificates automatically every 12 hours.
    entrypoint: |
      /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
  certbot-web:
  certbot-certs:
